hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.job.chdir=True
    - hydra.mode=MULTIRUN
    task: []
  job:
    name: main
    chdir: true
    override_dirname: ''
    id: ???
    num: ???
    config_name: integrator
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.1'
    cwd: /home/mmowbray/Github/feasibility/mu.F/src
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/mmowbray/Github/feasibility/mu.F/src/config
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      graph: tablet_press
      init: tablet_press
      reconstruction: tablet_press
      samplers: tablet_press
      solvers: tablet_press
      surrogate: tablet_press
      model: tablet_press
      case_study: tablet_press
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
case_study:
  case_study: tablet_press
  vmap_evaluations: true
  adjacency_matrix:
  - - 0
    - 1
    - 0
  - - 0
    - 0
    - 1
  - - 0
    - 0
    - 0
  n_aux_args:
    (0,1): 0
    (1,2): 0
    node_0: 0
    node_1: 0
    node_2: 0
  n_design_args:
  - 3
  - 2
  - 2
  n_input_args:
    (0,1): 2
    (1,2): 1
  KS_bounds:
    design_args:
    - - - 2.7
        - 3.3
      - - 25
        - 28
      - - 1080
        - 1160
    - - - 0.2
        - 0.4
      - - 230
        - 270
    - - - 100
        - 300
      - - 300
        - 500
    aux_args:
    - - - None
        - None
    - - - None
        - None
    - - - None
        - None
  fn_evals:
  - 0
  - 0
  - 0
  unit_op:
  - steady_state
  - steady_state
  - steady_state
  unit_params_fn:
  - None
  - None
  - None
  n_theta:
  - 2
  - 2
  - 2
  parameters_samples:
  - - c:
      - 0.001
      - -0.0
      w: 0.5
    - c:
      - 0.003
      - -0.002
      w: 0.5
  - - c:
      - 0.0004
      - -0.0004
      w: 0.5
    - c:
      - 0.0003
      - -0.0003
      w: 0.5
  - - c:
      - 0.002
      - -0.001
      w: 0.5
    - c:
      - 0.004
      - -0.003
      w: 0.5
  parameters_best_estimate:
  - - 0
    - 0
  - - 0
    - 0
  - - 0
    - 0
  extendedDS_bounds:
  - None
  - None
  - None
  global_n_aux_args: 0
  design_space_dimensions:
  - 'N1: P1'
  - 'N1: P2'
  - 'N1: P3'
  - 'N2: P1'
  - 'N2: P2'
  - 'N3: P1'
  - 'N3: P2'
  process_space_names:
  - - 'N1: P1'
    - 'N1: P2'
    - 'N1: P3'
  - - 'N2: P1'
    - 'N2: P2'
    - 'U1: API (kg/h)'
    - 'U1: Exc. (kg/h)'
  - - 'N3: P1'
    - 'N3: P2'
    - Porosity
  mode:
  - backward
  evaluation_mode: jax-pmap
model:
  root_node_inputs:
  - None
  constraint:
    auxiliary: None
    unit1_volume: 0.2
    unit2_volume: 1.9
    die_radius: 0.017
    tablet_size:
    - 0.014
    - 0.0175
    tablet_composition:
    - 0.09
    - 0.11
    tablet_hardness:
    - 4.8
    - 4.88
  unit_1_args:
    bulk_density:
    - 250
    - -0.372
    - 9
    - 0.000225
    mean_residence_time:
    - 100
    - 100
    - 1
  unit_2_args:
    bulk_density:
    - 250
    - 23.31
    - -55.16
    - -0.0507
    hold_up_mass:
    - 680
    - 5.449
    - -1.875
    - 0.00176
    - -8.22e-06
    particle_density:
    - 318.59
    - 45.1
    - -117.45
    - 0.022
  blender_density:
    include_lubricant: true
  unit_3_args:
    main_comp_kawakita: 0.1
    pre_comp_kawakita: 0.25
    initial_volume_in_die: 2.025e-05
    critical_density: 0.99
    hardness_zero_porosity: 5
  node_aux:
  - None
  - None
  - None
  - None
  - None
  - None
surrogate:
  surrogate_forward:
    drop_uncertain_params: false
    ann:
      hidden_size_options:
      - - 50
        - 50
      - - 25
        - 10
      - - 10
        - 10
      activation_functions:
      - - tanh
        - tanh
      decaying_lr_and_clip_param: true
      learning_rate: 0.01
      terminal_lr: 1.0e-05
      num_epochs: 1000
      min_delta: 1.0e-05
      patience: 10
      batch_size: 264
    gp:
      kernel: Matern
      n_restarts_optimizer: 10
      alpha: 0.1
      normalize_y: true
      noise: gaussian
  classifier: true
  classifier_selection: ANN
  regressor_selection: ANN
  probability_map: false
  subsample_size: 100000
  num_folds: 2
  index_on: 1
  classifier_args:
    standardised: true
    svm:
      kernel:
      - rbf
      C:
      - 20
      - 10
      - 2.5
      - 1
      - 0.1
      gamma:
      - 0.2
      - 1
      - 0.5
      - 2
      - 4
      - 6
      probability:
      - false
    ann:
      hidden_size_options:
      - - 50
        - 50
      - - 25
        - 10
      - - 10
        - 10
      activation_functions:
      - - tanh
        - tanh
      decaying_lr_and_clip_param: true
      learning_rate: 0.01
      terminal_lr: 1.0e-05
      num_epochs: 1000
      min_delta: 1.0e-06
      patience: 50
      batch_size: 264
  forward_evaluation_surrogate: true
solvers:
  penalty_method_coupler:
    n_starts: 4
    n_iterates: 7
    mu_increment: 2.5
    mu_og: 2.5
    ftol0: 0.001
    ftol_increment: 0.01
    augmented_grad_tol: 0.01
    augmented_constr_tol: 0.01
    ftol_min: 1.0e-05
    augmented_obj_tol: 0.001
  evaluation_mode:
    forward: ray
    backward: jax-pmap
  forward_coupling_solver: general_constrained_nlp
  backward_coupling_solver: box_constrained_nlp
  forward_coupling:
    max_solution_time: 1.0
    parallelised: true
    n_starts: 4
    casadi_ipopt_options:
      maxiter: 1000
      verbose: false
      tol: 1.0e-06
      options:
        verbose: 0
        maxiter: 1000
        disp: false
    jax_opt_options:
      n_starts: 4
      n_iterates: 7
      mu_increment: 2.5
      mu_og: 2.5
      ftol0: 0.001
      ftol_increment: 0.01
      augmented_grad_tol: 0.01
      augmented_constr_tol: 0.01
      ftol_min: 1.0e-05
      augmented_obj_tol: 0.001
  standardised: false
  backward_coupling:
    n_starts: 4
    jax_opt_options:
      error_tol: 1.0e-06
      ftol0: 0.001
      ftol_increment: 0.01
      augmented_grad_tol: 0.01
      augmented_constr_tol: 0.01
      ftol_min: 1.0e-05
      augmented_obj_tol: 0.001
samplers:
  target_reliability: 1.0
  unit_wise_target_reliability:
  - 1.0
  - 1.0
  - 1.0
  deus:
    activity_type: dsc
  notion_of_feasibility: positive
  ku_approximation: box
  vol_scale: 0.02
  ns:
    n_live: 3500
    final_sample_live: 3500
    n_replacements: 50
    n_iter: 15000
    f0: 0.1
    alpha: 0.2
    prior: Uniform
    rejector: suob-ellipsoid
    log_evidence_estimation: true
reconstruction:
  reconstruct:
  - false
  - true
  plot_reconstruction: nominal_map
  reconstruction_scheme: uniform
init:
  sobol_samples: 8192
  sampler: sobol
graph: {}
max_devices: 10
formulation: deterministic
method: direct
max_uncertain_samples: 50
