case_study: temporal_study

vmap_evaluations: True

adjacency_matrix: None

n_design_args: 2

n_aux_args: None

n_input_args:
  ('n','n'+1): 1

KS_bounds:
  - - - 0
      - 10
  - - - 0
      - 10

parameters_samples: 
  - [{'c': [0.], 'w': 1.},{'c': [0.], 'w': 1.}]

parameters_best_estimate: 
  - [0.]

extendedDS_bounds: [None]

design_space_dimensions:
- 'X'
- 'Y'

global_n_aux_args: 0

process_space_names:
  - ['X', 'Y']

mode:
  - backward

evaluation_mode: 'jax-pmap'