
defaults:
  - case_study: tablet_press #serial_batch_reactor
  - model: tablet_press #serial_batch_reactor
  - surrogate: tablet_press #serial_batch_reactor
  - solvers: tablet_press #serial_batch_reactor
  - samplers: tablet_press #serial_batch_reactor
  - reconstruction: tablet_press #serial_batch_reactor
  - init: tablet_press #serial_batch_reactor
  - graph: tablet_press #serial_batch_reactor

max_devices: 10
formulation: probabilistic # deterministic
method: direct # decomposition # #