
defaults:
  - case_study: serial_batch_reactor #tablet_press #
  - model: serial_batch_reactor # tablet_press #serial_batch_reactor
  - surrogate: serial_batch_reactor # tablet_press #serial_batch_reactor
  - solvers: serial_batch_reactor # tablet_press #serial_batch_reactor
  - samplers: serial_batch_reactor # tablet_press #serial_batch_reactor
  - reconstruction: serial_batch_reactor # tablet_press #serial_batch_reactor
  - init: serial_batch_reactor # tablet_press #serial_batch_reactor
  - graph: serial_batch_reactor # tablet_press #serial_batch_reactor

max_devices: 10
formulation: probabilistic # deterministic # 
method: decomposition # direct #
max_uncertain_samples: 50