
defaults:
  - case_study: convex_estimator # serial_batch_reactor # tablet_press #  
  - model: convex_estimator # serial_batch_reactor #tablet_press #serial_batch_reactor
  - surrogate: convex_estimator # serial_batch_reactor #tablet_press #serial_batch_reactor
  - solvers: convex_estimator # serial_batch_reactor #tablet_press #serial_batch_reactor
  - samplers: convex_estimator # serial_batch_reactor #tablet_press #serial_batch_reactor
  - reconstruction: convex_estimator # serial_batch_reactor #tablet_press #serial_batch_reactor
  - init: convex_estimator # serial_batch_reactor #tablet_press #serial_batch_reactor
  - graph: convex_estimator # serial_batch_reactor #tablet_press #serial_batch_reactor

max_devices: 10
formulation: deterministic # probabilistic #  # 
method: decomposition #decomposition # direct #
max_uncertain_samples: 50