
defaults:
  - case_study: rl_pcgym #tablet_press # serial_batch_reactor # tablet_press #
  - model: rl_pcgym #tablet_press # serial_batch_reactor #tablet_press #serial_batch_reactor
  - surrogate: rl_pcgym #tablet_press # serial_batch_reactor #tablet_press #serial_batch_reactor
  - solvers: rl_pcgym #tablet_press # serial_batch_reactor #tablet_press #serial_batch_reactor
  - samplers: rl_pcgym #tablet_press # serial_batch_reactor #tablet_press #serial_batch_reactor
  - reconstruction: rl_pcgym #tablet_press # serial_batch_reactor #tablet_press #serial_batch_reactor
  - init: rl_pcgym #tablet_press # serial_batch_reactor #tablet_press #serial_batch_reactor
  - graph: rl_pcgym #tablet_press # serial_batch_reactor #tablet_press #serial_batch_reactor

max_devices: 10
formulation: deterministic # probabilistic #  # 
method: decomposition #decomposition # direct #
max_uncertain_samples: 50