
surrogate_forward:
  drop_uncertain_params: False
  ann:
    hidden_size_options: 
      - [50, 50]
      - [25, 10]
      - [10, 10]
    activation_functions:
      - ['tanh', tanh]
    decaying_lr_and_clip_param: True
    learning_rate: 0.01
    terminal_lr: 0.00001  
    num_epochs: 1000 # 10 #50 # 50 # 500
    min_delta: 0.00001
    patience: 10
    batch_size: 264 #64
  gp:
    kernel: 'Matern'
    n_restarts_optimizer: 10
    alpha: 0.1
    normalize_y: True
    noise: 'gaussian'
    

classifier: true
classifier_selection: 'ANN' # or 'SVM'
regressor_selection: 'ANN' # or 'GP' 
probability_map: false

subsample_size: 100000
num_folds: 2

index_on: 1

classifier_args: 
  standardised: true
  svm: # these parameters must be provided as lists for Sklearn's GridSearchCV
    kernel: ['rbf']
    C: [20, 10, 2.5, 1, 0.1]
    gamma: [0.2, 1, 0.5, 2, 4, 6]
    probability: [False]
  ann:
    hidden_size_options:
      - [50, 50]
      - [25, 10]
      - [10, 10]
    activation_functions:
      - ['tanh', tanh]

    decaying_lr_and_clip_param: True
    learning_rate: 0.01
    terminal_lr: 0.00001  
    num_epochs: 1000 # 10 #50 # 50 # 500
    min_delta: 0.000001
    patience: 50
    batch_size: 264 #64


forward_evaluation_surrogate: true