case_study: constrained_rl

vmap_evaluations: False

adjacency_matrix:
  - [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  - [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  - [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0]
  - [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]
  - [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0]
  - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]
  - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]


n_design_args:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1

n_input_args:
  (0,1): 2
  (1,2): 2
  (2,3): 2
  (3,4): 2
  (4,5): 2
  (5,6): 2
  (6,7): 2
  (7,8): 2
  (8,9): 2
  (9,10): 2
  (10,11): 2

KS_bounds:  # unit, arg, b
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  - - - -1
      - 1
  

fn_evals: 
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0

unit_op:
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'

unit_params_fn:
  - None
  - None

n_theta:
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2
  - 2

parameters_samples: # list of list of dicts [node][[{c: [param], w: [param_weight in posteiror distribution]}]]  #  q = multivariate_normal([6.66e-06, 0.0010335], [[0.00001e-06, 0.000001e-08],[0.000001e-08, 0.0000005]])
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]
  - [{'c': [1,1], 'w': 0.5}, {'c': [1,1], 'w': 0.5}]

parameters_best_estimate: # list of lists [node][[param1]] most likely estimate
  - [1, 1]
  - [1, 1]
  - [1, 1]
  - [1, 1]
  - [1, 1]
  - [1, 1]
  - [1, 1]
  - [1, 1]
  - [1, 1]
  - [1, 1]
  - [1, 1]
  - [1, 1]

extendedDS_bounds: [None, None, None, None, None, None, None, None, None, None, None, None]


design_space_dimensions:
  - 'Control 0'
  - 'Control 1'
  - 'Control 2'
  - 'Control 3'
  - 'Control 4'
  - 'Control 5'
  - 'Control 6'
  - 'Control 7'
  - 'Control 8'
  - 'Control 9'
  - 'Control 10'


process_space_names:
  - ['Control 0']
  - ['Control 1']
  - ['Control 2']
  - ['Control 3']
  - ['Control 4']
  - ['Control 5']
  - ['Control 6']
  - ['Control 7']
  - ['Control 8']
  - ['Control 9']
  - ['Control 10']


mode:
  - backward

evaluation_mode: 'jax-pmap' #serial