case_study: tablet_press

vmap_evaluations: True

adjacency_matrix:
  - [0, 1, 0]
  - [0, 0, 1]
  - [0, 0, 0]

n_aux_args:
  # auxiliary arguments per edge
  (0,1): 0
  (1,2): 0
  # auxiliary arguments per node
  node_0: 0
  node_1: 0
  node_2: 0


n_design_args:
  - 3
  - 2
  - 2

n_input_args:
  (0,1): 2
  (1,2): 1

KS_bounds:
  design_args: # unit, arg, b
  - - - 2.7
      - 3.3
    - - 25
      - 28
    - - 1080
      - 1160
  - - - 0.2
      - 0.4
    - - 230
      - 270
  - - - 100
      - 300
    - - 300
      - 500
  aux_args:
  - - - None    
      - None
  - - - None
      - None
  - - - None
      - None


fn_evals: 
  - 0
  - 0
  - 0

unit_op:
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'

unit_params_fn:
  - None
  - None
  - None

n_theta:
  - 2
  - 2
  - 2

parameters_samples: # list of list of dicts [node][[{c: [param], w: [param_weight in posteiror distribution]}]]
  - - c: [.001, -0.00]
      w: .5
    - c: [0.003, -0.002]
      w: .5
  - - c: [0.0004, -0.0004]
      w: .5
    - c: [0.0003, -0.0003]
      w: .5
  - - c: [0.002, -0.001]
      w: .5
    - c: [0.004, -0.003]
      w: .5

parameters_best_estimate: # list of lists [node][[param1]] most likely estimate
  - [0, 0]
  - [0, 0]
  - [0, 0]

extendedDS_bounds: [None, None, None]

global_n_aux_args: 0

design_space_dimensions:
  - 'N1: P1' #'U1: API (kg/h)'
  - 'N1: P2' #'U1: Exc. (kg/h)'
  - 'N1: P3' #'U1: Blade speed (RPM)'
  - 'N2: P1' # 'U2: Lubricant (kg/h)'
  - 'N2: P2' #'U2: Blade speed (RPM)'
  - 'N3: P1' #'U3: P.C.P. (MPa)'
  - 'N3: P2' # 'U3: M.C.P. (MPa)'
process_space_names:
  - - 'N1: P1' # 'U1: API (kg/h)'
    - 'N1: P2' # 'U1: Exc. (kg/h)'
    - 'N1: P3' # 'U1: Blade speed (RPM)'
  - - 'N2: P1' # 'U2: Lubricant (kg/h)'
    - 'N2: P2' #'U2: Blade speed (RPM)'
    - 'U1: API (kg/h)'
    - 'U1: Exc. (kg/h)'
  - - 'N3: P1' #'U3: P.C.P. (MPa)'
    - 'N3: P2' # 'U3: M.C.P. (MPa)'
    - Porosity


mode:
  - backward 
  #- backward-forward
  

evaluation_mode: 'jax-pmap' #serial