case_study: tablet_press

vmap_evaluations: True

adjacency_matrix:
  - [0, 1, 0]
  - [0, 0, 1]
  - [0, 0, 0]

n_design_args:
  - 3
  - 2
  - 2

n_input_args:
  (0,1): 2
  (1,2): 1

KS_bounds:
  - - - 2.7
      - 3.3
    - - 25
      - 28
    - - 1080
      - 1160
  - - - 0.2
      - 0.4
    - - 230
      - 270
  - - - 100
      - 300
    - - 300
      - 500


fn_evals: 
  - 0
  - 0
  - 0

unit_op:
  - 'steady_state'
  - 'steady_state'
  - 'steady_state'

unit_params_fn:
  - None
  - None
  - None

n_theta:
  - 2
  - 2
  - 2

parameters_samples: # list of list of dicts [node][[{c: [param], w: [param_weight in posteiror distribution]}]]
  - - c: [.001, -0.00]
      w: .5
    - c: [0.003, -0.002]
      w: .5
  - - c: [0.0004, -0.0004]
      w: .5
    - c: [0.0003, -0.0003]
      w: .5
  - - c: [0.002, -0.001]
      w: .5
    - c: [0.004, -0.003]
      w: .5

parameters_best_estimate: # list of lists [node][[param1]] most likely estimate
  - [0, 0]
  - [0, 0]
  - [0, 0]

extendedDS_bounds: [None, None, None]


design_space_dimensions: 
- 'U1: API (kg/h)'
- 'U1: Exc. (kg/h)'
- 'U1: Blade speed (RPM)'
- 'U2: Lubricant (kg/h)'
- 'U2: Blade speed (RPM)'
- 'U3: P.C.P. (MPa)'
- 'U3: M.C.P. (MPa)'


process_space_names: # create unit wise list
  - ['U1: API (kg/h)', 'U1: Exc. (kg/h)', 'U1: Blade speed (RPM)']
  - ['U2: Lubricant (kg/h)', 'U2: Blade speed (RPM)', 'U1: API (kg/h)', 'U1: Exc. (kg/h)']
  - ['U3: P.C.P. (MPa)', 'U3: M.C.P. (MPa)', 'Porosity']



mode:
  - backward 
  - backward-forward
  

evaluation_mode: 'jax-pmap' #serial