
target_reliability: 0.95
deus: 
  activity_type: 'dsc'

notion_of_feasibility: 'positive'
ku_approximation: 'box'
vol_scale: 0.05

ns:
  n_live: 100
  final_sample_live: 100  
  n_replacements: 50 
  n_iter: 15000 
  f0: 0.1
  alpha: 0.2
  prior: Uniform
  rejector: suob-ellipsoid
