
target_reliability: 0.99
deus: 
  activity_type: 'dsc'

notion_of_feasibility: 'positive'

ns:
  n_live: 50
  final_sample_live: 4000 
  n_replacements: 500 
  n_iter: 15000 
  f0: 0.1
  alpha: 0.2
  prior: Uniform
  rejector: suob-ellipsoid
