
target_reliability: 1.
unit_wise_target_reliability: [1., 1.]
deus: 
  activity_type: 'dsc'

notion_of_feasibility: 'positive'
ku_approximation: 'box'
vol_scale: 0.01

ns:
  n_live: 100
  final_sample_live: 100  
  n_replacements: 50 
  n_iter: 15000 
  f0: 0.3
  alpha: 0.3
  prior: Uniform
  rejector: suob-ellipsoid
  log_evidence_estimation: True


bo:
  bounds: 
    max: 0.49
    min: 0
  num_initial_points: 4
  num_iterations: 4 # subsequent to initial samples