# dynamics definition

arrhenius:
  EA: 
    - - 158992.00000000003 # AE R1
      - 158992.00000000003 # AE R2
      - 158992.00000000003 # AE R3
      - 158992.00000000003 # AE R4
    - - 80073.392 # AE R1
      - 40036.696 # AE R2
  R: 8.314 # ideal gas constant


root_node_inputs:
  - - 2000. # component 1
    - 0. # component 2
    - 0. # component 3
    - 0. # component 4
    - 0. # component 5


constraint:
  purity_u1: 0.65
  purity_u2: 0.81
  auxiliary: 'None'


integration:
  scheme: tsit5  # dopri8
  step_size_controller: pid
  t0: 0
  tf: 1
  dt0: 1.0e-1
  max_steps: 10000