# dynamics definition

arrhenius:
  EA: 
    - 2500.2 # AE R1
    - 5000.1 # AE R2
  A:
    - 6.66e-06 # pre-exponent. factor R1
    - 0.0010335 # pre-exponent. factor R2
  R: 8.314 # ideal gas constant


x0:
  - 2000 # component 1
  - 0 # component 2
  - 0 # component 3

