# steady state parameters definition

root_node_inputs:
  - None 


constraint:
  auxiliary: 'None'
  unit1_volume: 0.2
  unit2_volume: 1.9
  die_radius: 0.017
  tablet_size:
  - 0.014
  - 0.0175
  tablet_composition:
  - 0.09
  - 0.11
  tablet_hardness:
  - 4.8
  - 4.88
  
unit_1_args:
  bulk_density:
  - 250
  - -0.372
  - 9
  - 0.000225
  mean_residence_time:
  - 100
  - 100
  - 1
unit_2_args:
  bulk_density:
  - 250
  - 23.31
  - -55.16
  - -0.0507
  hold_up_mass:
  - 680
  - 5.449
  - -1.875
  - 0.00176
  - -8.22e-06
  particle_density:
  - 318.59
  - 45.1
  - -117.45
  - 0.022
    
blender_density:
  include_lubricant: True

unit_3_args:
  main_comp_kawakita: 0.1 #TODO: add more args
  pre_comp_kawakita: 0.25
  initial_volume_in_die: 0.00002025
  critical_density: 0.99 # 0.01
  hardness_zero_porosity: 5 # NOTE can change


node_aux: 
  - None
  - None
  - None
  - None
  - None
  - None